# Generated by Django 4.2.6 on 2023-10-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_jwt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
